# Generated by Django 5.0.6 on 2024-06-22 13:57

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('content_fr', models.TextField(null=True, verbose_name='content')),
                ('content_en', models.TextField(null=True, verbose_name='content')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='publication_date')),
                ('publication_date_fr', models.DateField(auto_now_add=True, null=True, verbose_name='publication_date')),
                ('publication_date_en', models.DateField(auto_now_add=True, null=True, verbose_name='publication_date')),
                ('embedding', pgvector.django.VectorField(dimensions=1536)),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
    ]
