# Generated by Django 5.0.6 on 2024-06-22 14:32

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initital'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=pgvector.django.HnswIndex(ef_construction=24, fields=['embedding'], m=10, name='gpt_vectors_index', opclasses=['vector_cosine_ops']),
        ),
    ]
