# Generated by Django 5.0.6 on 2024-06-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AddField(
            model_name='article',
            name='content_af',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ar',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ar_dz',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ast',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_az',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_be',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_bg',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_bn',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_br',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_bs',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ca',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ckb',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_cs',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_cy',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_da',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_de',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_dsb',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_el',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_en_au',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_en_gb',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_eo',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_es',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_es_ar',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_es_co',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_es_mx',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_es_ni',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_es_ve',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_et',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_eu',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_fa',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_fi',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_fr',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_fy',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ga',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_gd',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_gl',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_he',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_hi',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_hr',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_hsb',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_hu',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_hy',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ia',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ig',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ind',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_io',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_is',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_it',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ja',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ka',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_kab',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_kk',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_km',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_kn',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ko',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ky',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_lb',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_lt',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_lv',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_mk',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ml',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_mn',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_mr',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ms',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_my',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_nb',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ne',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_nl',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_nn',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_os',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_pa',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_pl',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_pt',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_pt_br',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ro',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_sk',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_sl',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_sq',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_sr',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_sr_latn',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_sv',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_sw',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ta',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_te',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_tg',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_th',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_tk',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_tr',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_tt',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_udm',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ug',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_uk',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ur',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_vi',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_zh_hans',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_zh_hant',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_af',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ar',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ar_dz',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ast',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_az',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_be',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_bg',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_bn',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_br',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_bs',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ca',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ckb',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_cs',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_cy',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_da',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_de',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_dsb',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_el',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_en',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_en_au',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_en_gb',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_eo',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_es',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_es_ar',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_es_co',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_es_mx',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_es_ni',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_es_ve',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_et',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_eu',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_fa',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_fi',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_fr',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_fy',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ga',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_gd',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_gl',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_he',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_hi',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_hr',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_hsb',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_hu',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_hy',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ia',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ig',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ind',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_io',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_is',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_it',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ja',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ka',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_kab',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_kk',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_km',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_kn',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ko',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ky',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_lb',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_lt',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_lv',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_mk',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ml',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_mn',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_mr',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ms',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_my',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_nb',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ne',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_nl',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_nn',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_os',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_pa',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_pl',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_pt',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_pt_br',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ro',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ru',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_sk',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_sl',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_sq',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_sr',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_sr_latn',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_sv',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_sw',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ta',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_te',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_tg',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_th',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_tk',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_tr',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_tt',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_udm',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ug',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_uk',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_ur',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_uz',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_vi',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_zh_hans',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date_zh_hant',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_af',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ar_dz',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ast',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_az',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_be',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_bg',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_bn',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_br',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_bs',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ca',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ckb',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_cs',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_cy',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_da',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_de',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_dsb',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_el',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en_au',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en_gb',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_eo',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_es_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_es_co',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_es_mx',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_es_ni',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_es_ve',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_et',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_eu',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fi',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fy',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ga',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_gd',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_gl',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_he',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_hi',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_hr',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_hsb',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_hu',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_hy',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ia',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ig',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ind',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_io',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_is',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_it',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ja',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ka',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_kab',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_km',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_kn',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ko',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_lb',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_lt',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_lv',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_mk',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ml',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_mn',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_mr',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ms',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_my',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_nb',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ne',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_nl',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_nn',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_os',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_pa',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_pl',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_pt',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_pt_br',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ro',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_sk',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_sl',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_sq',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_sr',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_sr_latn',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_sv',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_sw',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ta',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_te',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_tg',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_th',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_tk',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_tt',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_udm',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ug',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ur',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_vi',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_zh_hant',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(auto_now_add=True, verbose_name='publication_date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
